#!bin/bash

# CREATED X SHARKCODE

# APRENDIZ

#               COLORES RESALTADOS
negro="\e[1;30m"
azul="\e[1;34m"
verde="\e[1;32m"
cian="\e[1;36m"
rojo="\e[1;31m"
purpura="\e[1;35m"
amarillo="\e[1;33m"
blanco="\e[1;37m"
#                 COLORES BAJOS
black="\e[0;30m"
blue="\e[0;34m"
green="\e[0;32m"
cyan="\e[0;36m"
R="\e[0;31m"
purple="\e[0;35m"
yellow="\e[0;33m"
W="\e[0;37m"
#                  BANNER DE TEXTO
BannerPASS(){
	sleep 0.5
	clear
echo -e "
██████╗  █████╗ ███████╗███████╗    ██╗    ██╗ ██████╗ ██████╗ ██████╗ 
██╔══██╗██╔══██╗██╔════╝██╔════╝    ██║    ██║██╔═══██╗██╔══██╗██╔══██╗
██████╔╝███████║███████╗███████╗    ██║ █╗ ██║██║   ██║██████╔╝██║  ██║
██╔═══╝ ██╔══██║╚════██║╚════██║    ██║███╗██║██║   ██║██╔══██╗██║  ██║
██║     ██║  ██║███████║███████║    ╚███╔███╔╝╚██████╔╝██║  ██║██████╔╝
╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝     ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═════╝ 
                         created by sharkcode
" | lolcat
}
MenuPASS(){
	sleep 0.5
	BannerPASS
echo -e "${rojo}[${blanco} ¿? ${rojo}]${rojo} >>>${blanco} MENU V1 PRIMERA VERSION"
echo ""
echo -e "${rojo}[${blanco} 01 ${rojo}]${rojo} >>>${blanco} Crear contraseña (100% SEGURA)${rojo} :)"
echo -e "${rojo}[${blanco} 02 ${rojo}]${rojo} >>>${blanco} Desofuscar contraseña (100% SEGURO)${rojo} :)"
echo ""
echo -e "${rojo}[${blanco} 05 ${rojo}]${rojo} >>>${blanco} Salir :("
echo -e -n "${rojo}
${rojo}[${blanco} :D ${rojo}]${rojo} >>>${blanco} Escribe una opcion${rojo} :)

${rojo}[${blanco} >> ${rojo}]${red} >>>" ${blanco}
read -r Preguntas

if [[ "${Preguntas}" == "1" || "${Preguntas}" == "01" ]]; then
	clear
	BannerPASS
echo -e -n "${rojo}
${rojo}[${blanco} :D ${rojo}]${rojo} >>>${blanco} Escribe una contraseña para ofuscar${rojo} :)

${rojo}[${blanco} :/ ${rojo}]${rojo} >>>${blanco} Ejemplo: CalaverisYT ${verde}(NO ESPACIOS)${rojo} :)

${rojo}[${blanco} >> ${rojo}]${red} >>>" ${blanco}
read -r Pass

echo "$Pass" > cuaking.txt
base64 cuaking.txt > /dev/null 2>&1
base64 cuaking.txt > OfuskPass

echo ""
echo -e "${rojo}[${blanco} :D ${rojo}]${rojo} >>>${blanco} Tu contraseña esta lista en el archivo OfuskPass${rojo} :D"
echo ""
sleep 3
echo -e "${rojo}[${blanco} ¿? ${rojo}]${rojo} >>>${blanco} Presiona ${verde}ENTER ${blanco} para continuar"
read $ENTER

MenuPASS

elif [[ "${Preguntas}" == "2" || "${Preguntas}" == "02" ]]; then
	clear
	BannerPASS
echo -e -n "${rojo}
${rojo}[${blanco} :D ${rojo}]${rojo} >>>${blanco} Escribe una ruta para desofuscar la password

${rojo}[${blanco} :/ ${rojo}]${rojo} >>>${blanco} Ejemplo:/data/data/com.termux/files/home/ScriptKiddie/uwu.sh

${rojo}[${blanco} >> ${rojo}]${red} >>>" ${blanco}
read Ruta

base64 $Ruta > PassDesofusk.txt
echo -e "${rojo}
${rojo}[${blanco} :D ${rojo}]${rojo} >>>${blanco} La contraseña desofuscada se encuentra en el archivo : PassDesofusk.txt"
echo ""
sleep 3
echo -e "${rojo}[${blanco} ¿? ${rojo}]${rojo} >>>${blanco} Presiona ${verde}ENTER ${blanco}Para continuar"
read $ENTER

MenuPASS

elif [[ "${Preguntas}" == "5" || "${Preguntas}" == "05" ]]; then
		clear
figlet Adios.. | lolcat
echo -e "${verde} Gracias por ocupar mi script adios !!
te amo <3 atte. Sharkcode"
          sleep 3
          exit
else
echo -e "${rojo}
OPCIÓN INCORRECTA" 
	sleep 2
	MenuPASS
fi
}
MenuPASS

